---
abstract: 'SOAP client for CLI with YAML and JSON input'
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
build_requires:
  App::FatPacker: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-soapcli
provides:
  App::soapcli:
    file: lib/App/soapcli.pm
    version: 0.02
requires:
  File::Slurp: 0
  Getopt::Long::Descriptive: 0
  HTTP::Tiny: 0
  JSON::PP: 0
  XML::Compile::SOAP: 0
  YAML::Syck: 0
  YAML::XS: 0
  constant::boolean: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=App-soapcli
  license: http://dev.perl.org/licenses/
  repository: http://github.com/dex4er/soapcli
version: 0.02
